server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    key: ${JWT_SECRET_KEY}
    access: ${JWT_ACCESS}
    refresh: ${JWT_REFRESH}

  jpa:
    database:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update